/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const PortfolioIndexLazyImport = createFileRoute('/portfolio/')()
const PortfolioAboutLazyImport = createFileRoute('/portfolio/about')()
const PortfolioSkillsTypeLazyImport = createFileRoute(
  '/portfolio/skills/type',
)()
const PortfolioSkillsTailwindLazyImport = createFileRoute(
  '/portfolio/skills/tailwind',
)()
const PortfolioSkillsSvelteLazyImport = createFileRoute(
  '/portfolio/skills/svelte',
)()
const PortfolioSkillsReactLazyImport = createFileRoute(
  '/portfolio/skills/react',
)()
const PortfolioSkillsNodeLazyImport = createFileRoute(
  '/portfolio/skills/node',
)()
const PortfolioSkillsNextLazyImport = createFileRoute(
  '/portfolio/skills/next',
)()
const PortfolioSkillsJsLazyImport = createFileRoute('/portfolio/skills/js')()
const PortfolioSkillsHtmlLazyImport = createFileRoute(
  '/portfolio/skills/html',
)()

// Create/Update Routes

const PortfolioIndexLazyRoute = PortfolioIndexLazyImport.update({
  path: '/portfolio/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/portfolio/index.lazy').then((d) => d.Route),
)

const PortfolioAboutLazyRoute = PortfolioAboutLazyImport.update({
  path: '/portfolio/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/portfolio/about.lazy').then((d) => d.Route),
)

const PortfolioSkillsTypeLazyRoute = PortfolioSkillsTypeLazyImport.update({
  path: '/portfolio/skills/type',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/portfolio/skills/type.lazy').then((d) => d.Route),
)

const PortfolioSkillsTailwindLazyRoute =
  PortfolioSkillsTailwindLazyImport.update({
    path: '/portfolio/skills/tailwind',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/portfolio/skills/tailwind.lazy').then((d) => d.Route),
  )

const PortfolioSkillsSvelteLazyRoute = PortfolioSkillsSvelteLazyImport.update({
  path: '/portfolio/skills/svelte',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/portfolio/skills/svelte.lazy').then((d) => d.Route),
)

const PortfolioSkillsReactLazyRoute = PortfolioSkillsReactLazyImport.update({
  path: '/portfolio/skills/react',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/portfolio/skills/react.lazy').then((d) => d.Route),
)

const PortfolioSkillsNodeLazyRoute = PortfolioSkillsNodeLazyImport.update({
  path: '/portfolio/skills/node',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/portfolio/skills/node.lazy').then((d) => d.Route),
)

const PortfolioSkillsNextLazyRoute = PortfolioSkillsNextLazyImport.update({
  path: '/portfolio/skills/next',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/portfolio/skills/next.lazy').then((d) => d.Route),
)

const PortfolioSkillsJsLazyRoute = PortfolioSkillsJsLazyImport.update({
  path: '/portfolio/skills/js',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/portfolio/skills/js.lazy').then((d) => d.Route),
)

const PortfolioSkillsHtmlLazyRoute = PortfolioSkillsHtmlLazyImport.update({
  path: '/portfolio/skills/html',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/portfolio/skills/html.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portfolio/about': {
      id: '/portfolio/about'
      path: '/portfolio/about'
      fullPath: '/portfolio/about'
      preLoaderRoute: typeof PortfolioAboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/portfolio/skills/html': {
      id: '/portfolio/skills/html'
      path: '/portfolio/skills/html'
      fullPath: '/portfolio/skills/html'
      preLoaderRoute: typeof PortfolioSkillsHtmlLazyImport
      parentRoute: typeof rootRoute
    }
    '/portfolio/skills/js': {
      id: '/portfolio/skills/js'
      path: '/portfolio/skills/js'
      fullPath: '/portfolio/skills/js'
      preLoaderRoute: typeof PortfolioSkillsJsLazyImport
      parentRoute: typeof rootRoute
    }
    '/portfolio/skills/next': {
      id: '/portfolio/skills/next'
      path: '/portfolio/skills/next'
      fullPath: '/portfolio/skills/next'
      preLoaderRoute: typeof PortfolioSkillsNextLazyImport
      parentRoute: typeof rootRoute
    }
    '/portfolio/skills/node': {
      id: '/portfolio/skills/node'
      path: '/portfolio/skills/node'
      fullPath: '/portfolio/skills/node'
      preLoaderRoute: typeof PortfolioSkillsNodeLazyImport
      parentRoute: typeof rootRoute
    }
    '/portfolio/skills/react': {
      id: '/portfolio/skills/react'
      path: '/portfolio/skills/react'
      fullPath: '/portfolio/skills/react'
      preLoaderRoute: typeof PortfolioSkillsReactLazyImport
      parentRoute: typeof rootRoute
    }
    '/portfolio/skills/svelte': {
      id: '/portfolio/skills/svelte'
      path: '/portfolio/skills/svelte'
      fullPath: '/portfolio/skills/svelte'
      preLoaderRoute: typeof PortfolioSkillsSvelteLazyImport
      parentRoute: typeof rootRoute
    }
    '/portfolio/skills/tailwind': {
      id: '/portfolio/skills/tailwind'
      path: '/portfolio/skills/tailwind'
      fullPath: '/portfolio/skills/tailwind'
      preLoaderRoute: typeof PortfolioSkillsTailwindLazyImport
      parentRoute: typeof rootRoute
    }
    '/portfolio/skills/type': {
      id: '/portfolio/skills/type'
      path: '/portfolio/skills/type'
      fullPath: '/portfolio/skills/type'
      preLoaderRoute: typeof PortfolioSkillsTypeLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  PortfolioAboutLazyRoute,
  PortfolioIndexLazyRoute,
  PortfolioSkillsHtmlLazyRoute,
  PortfolioSkillsJsLazyRoute,
  PortfolioSkillsNextLazyRoute,
  PortfolioSkillsNodeLazyRoute,
  PortfolioSkillsReactLazyRoute,
  PortfolioSkillsSvelteLazyRoute,
  PortfolioSkillsTailwindLazyRoute,
  PortfolioSkillsTypeLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/portfolio/about",
        "/portfolio/",
        "/portfolio/skills/html",
        "/portfolio/skills/js",
        "/portfolio/skills/next",
        "/portfolio/skills/node",
        "/portfolio/skills/react",
        "/portfolio/skills/svelte",
        "/portfolio/skills/tailwind",
        "/portfolio/skills/type"
      ]
    },
    "/portfolio/about": {
      "filePath": "portfolio/about.lazy.tsx"
    },
    "/portfolio/": {
      "filePath": "portfolio/index.lazy.tsx"
    },
    "/portfolio/skills/html": {
      "filePath": "portfolio/skills/html.lazy.tsx"
    },
    "/portfolio/skills/js": {
      "filePath": "portfolio/skills/js.lazy.tsx"
    },
    "/portfolio/skills/next": {
      "filePath": "portfolio/skills/next.lazy.tsx"
    },
    "/portfolio/skills/node": {
      "filePath": "portfolio/skills/node.lazy.tsx"
    },
    "/portfolio/skills/react": {
      "filePath": "portfolio/skills/react.lazy.tsx"
    },
    "/portfolio/skills/svelte": {
      "filePath": "portfolio/skills/svelte.lazy.tsx"
    },
    "/portfolio/skills/tailwind": {
      "filePath": "portfolio/skills/tailwind.lazy.tsx"
    },
    "/portfolio/skills/type": {
      "filePath": "portfolio/skills/type.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
